### ISSUE TITLE
Reconnect naar web-socket werkt niet helemaal

### ISSUE THREAD

**Issue by JasperRab** [PlaceNL/rPlace2022#1]
Een reconnect zorgt ervoor dat het script crash.

```
INFO     [PlaceNL.cnc] Notified CNC server of drawn pixel.                                                                                                 PlaceNL.py:198
[04/03/22 12:52:29] WARNING  [PlaceNL.cnc] Connection to C&C websocket lost, trying again in one minute...                                                                     PlaceNL.py:504
[04/03/22 12:52:31] ERROR    [asyncio] Task exception was never retrieved                                                                                                 base_events.py:1753
                             future: <Task finished name='Task-2996' coro=<CNCOrderClient.ping() done, defined at
                             C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py:155> exception=ConnectionResetError('Cannot write to closing transport')>
                             Traceback (most recent call last):
                               File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py", line 158, in ping
                                 await self.ws.send_str(json.dumps({"type": "ping"}))
                               File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\client_ws.py", line 151, in send_str
                                 await self._writer.send(data, binary=False, compress=compress)
                               File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\http_websocket.py", line 690, in send
                                 await self._send_frame(message, WSMsgType.TEXT, compress)
                               File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\http_websocket.py", line 601, in _send_frame
                                 raise ConnectionResetError("Cannot write to closing transport")
                             ConnectionResetError: Cannot write to closing transport
Traceback (most recent call last):
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py", line 581, in <module>
    asyncio.run(main())
  File "C:\Users\media\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\media\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py", line 579, in main
    await asyncio.gather(*tasks)
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py", line 502, in cnc_update_task
    await cnc_client.receive_orders()
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\PlaceNL.py", line 165, in receive_orders
    await self.ws.send_str(json.dumps({"type": "getmap"}))
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\media\Desktop\PlaceNL\Python\rPlace2022\venv\lib\site-packages\aiohttp\http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by lrvdijk** [comment]
Thanks goede, ik ga het fixen

**Comment by lrvdijk** [comment]
Zou gefixed moeten zijn!
