### ISSUE TITLE
could not obtain access token

### ISSUE THREAD

**Issue by Sloth-on-meth** [PlaceNL/rPlace2022#2]
Traceback (most recent call last):
  File "/home/sam/placeNL/rPlace2022/PlaceNL.py", line 616, in <module>
    run()
  File "/home/sam/placeNL/rPlace2022/PlaceNL.py", line 612, in run
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/sam/placeNL/rPlace2022/PlaceNL.py", line 603, in main
    await asyncio.gather(*tasks)
  File "/home/sam/placeNL/rPlace2022/PlaceNL.py", line 530, in reddit_client_task
    async with RedditPlaceClient(session, username, password, user_agent) as place_client:
  File "/home/sam/placeNL/rPlace2022/PlaceNL.py", line 238, in __aenter__
    raise Exception("Could not obtain access token.")
Exception: Could not obtain access token.

**Comment by SpiderDead** [comment]
@Sloth-on-meth What is the command you are using? And do you have the latest version?

**Comment by Sloth-on-meth** [comment]
Python bot.py -u "username" "password"

**Comment by lrvdijk** [comment]
Do you have special characters in your password? In case you have a $ in your password, you'd have to escape it with like \\$.

I've also updated the code, which should provide with more error information if it still doesn't work.
