### ISSUE TITLE
2k update nog niet ready?

### ISSUE THREAD

**Issue by thomasvt1** [PlaceNL/rPlace2022#4]
```Traceback (most recent call last):
  File "/usr/local/bin/PlaceNL", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/PlaceNL.py", line 648, in run
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/PlaceNL.py", line 644, in main
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/PlaceNL.py", line 593, in reddit_client
    to_update = place_client.get_pixels_to_update(self.order_map)
  File "/usr/local/lib/python3.10/site-packages/PlaceNL.py", line 453, in get_pixels_to_update
    if not numpy.array_equal(order_map[row, col, :3], self.current_canvas[row, col, :3]):
IndexError: index 1949 is out of bounds for axis 0 with size 1000```

**Comment by lrvdijk** [comment]
As discussed in Discord, this was an old docker image 👍
