### ISSUE TITLE
crash (raspberry pi)

### ISSUE THREAD

**Issue by DaxMoorman** [PlaceNL/rPlace2022#7]
Traceback (most recent call last):
  File "/home/pi/./PlaceNL.py", line 693, in <module>
    run()
  File "/home/pi/./PlaceNL.py", line 689, in run
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/./PlaceNL.py", line 685, in main
    await asyncio.gather(*tasks)
  File "/home/pi/./PlaceNL.py", line 628, in reddit_client
    await place_client.load_full_map()
  File "/home/pi/./PlaceNL.py", line 454, in load_full_map
    canvas4 = await self.load_canvas(3)
  File "/home/pi/./PlaceNL.py", line 393, in load_canvas
    async with self.session.ws_connect(PLACE_WEBSOCKET, protocols=["graphql-ws"], headers=headers) as ws:
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by lrvdijk** [comment]
Hmm I believe that happens occasionally, the latest commit should be more robust to such errors.
